### ISSUE TITLE
Module Request: ember+

### ISSUE THREAD

**Issue by daniel3p4u** [bitfocus/companion-module-generic-emberplus#1]
Describe the feature
control devices using ember+ protocol

Is this platform dependent (windows, mac, ..)?
platform independent

Features to Include
- route signals
- get status
there are a lot of other options. in my usecase routing signals would be the main function

If documentation is required to implement, do you know where to find it?
ember+ is a protocol developed by lawo.
https://github.com/Lawo/ember-plus
Maybe that can help: https://www.npmjs.com/package/emberplus

Usecases
There are a lot of devices using ember+ for different functions
E.g. load settings, fire soft GPIs, trigger actions inside the device, change a 
parameter like the gain of a processing channel, routing video/audio signals
I would use it with Riedel mediornet but there is a lot professional broadcast equipment using ember+.

**Comment by bfcn** [comment]
Hi,

Thank you for your answer

I am trying to control a Mediornet (Micron) from Riedel to make video routing.
This system run with no operating system and I saw in the topic that a few people succeed to control this kind of devices for video routing. I am using the exact same settings from what I know but it doesn’t work.

As said in my first explanation, I already used Lawo tool to get the path and I tried to make matrix connexion using 3rd party ID minus 1 as explained.
Please find bellow my full explanations of what I tried:

I'm trying to use ember + protocol in last release (2.1.3) on a windows computer to control video routing of my Riedel Micron set but I can't make it works. I activated 3rd party ID's with Ember + protocol activated on mediorworks and added my primary master IP as ember + controller in Companion. Then I used Lawo software to get the right pass for video matrix (1.2.0.3) and used the Target and Source -1 I want to control but nothing is changed in my Micron routing. Connexion between Micron and Companion seams okay. Am I missing something here ?

Thank you for your help

Dorian

**Comment by lenstar** [comment]
> would it be possible to just get a path value on a bottom? Would like to monitor just some temputurs out a emberplus tree and power. Woul be nice to have someting like $(emberplus:path) in the bottom text

Would this already be possible?

**Comment by baltedewit** [comment]
This issue is about the initial development and inclusion of the module, please open new issues for any additional feature requests and problems with the module. Thanks in advance.

**Comment by MarcJacobin** [comment]
Hello, I am looking to connect my Riedel MediorNets in Compagnon. I saw in your message that via Ember+ it can work.
But I can't connect it, I know the IP, but I don't know what to Target, I can't find this information in MediorWorks.
![image](https://user-images.githubusercontent.com/124171815/216073380-e916c334-c2ef-4684-83d9-2cba6c1d8255.png)
Thanks very much

**Comment by dewiweb** [comment]
@MarcJacobin ,you have to declare a primary master for ember+ protocol in the "3rd party protocol" tab of mediorworks, then you have to configure IDs of connections you want to control in the same tab. Take a look at the Mediornet Application Notes Ember+ document downloadable on the Riedel Website. You can also download [Ember+ viewer](https://github.com/Lawo/ember-plus/releases) to check the avalaibility of your mediornet device as an Ember+ server.
