### ISSUE TITLE
Matrix connections not working

### ISSUE THREAD

**Issue by Zettrax** [bitfocus/companion-module-generic-emberplus#10]
Been trying to set up a companion server in a tiny OB-van, the main video matrix in the van is an Riedel Micron and I've been trying to set up some crosspoints through companion, I have the ember+ connection up with OK status, i use action emberplus: Matrix set connection and Matrix connect, use path 1.2.0.3 which should be the video matrix (looking at the Ember+ viewer) I have 3rd party interface set up. but nothing seems to be happening in the micron router at all, been trying a lot of different target and sources but nothing is happening, am i missing something?
![IMG_5303](https://user-images.githubusercontent.com/122486915/211912376-34b1b626-5e25-471a-be92-011e2acf01d3.jpg)
![IMG_5302](https://user-images.githubusercontent.com/122486915/211912396-761c735c-dda4-4c7a-b930-1f722c6d7469.jpg)

**Comment by glop24** [comment]
Hello Zettrax, 
I have exactly the same problem... 
Do you find a solution ?

**Comment by booguiseb** [comment]
Same here, Micron Riedel  with companion and the EMBER +, not able to connect in the matrix or change any label .
