### ISSUE TITLE
Beta or newer Release stuck at Status Unknown and not working

### ISSUE THREAD

**Issue by schindlerit1984** [bitfocus/companion-module-generic-emberplus#11]
Hi, 

been using the newest versions 3.+ and not getting ember+ to work at all again. the module is Stuck at status unknown and not opening any connections settings etc. 

since we are using this with Mediornet via Ember+ and VSM its kinda key for me to get it up again. 

any ideas why this is happening ?

**Comment by Julusian** [comment]
This should be fixed in build 5665

**Comment by schindlerit1984** [comment]
Still does say unknown in latest build

**Comment by Julusian** [comment]
5665 hasnt finished building yet. itll be ready to try in 5-20 minutes.

are you on the experimental builds? dont use those.

**Comment by schindlerit1984** [comment]
oh tanks. would just be for testing no worries.

**Comment by schindlerit1984** [comment]
beta 5665 gives no errors anymore. need to test with mediornet to see my functions working or not - thanks for the fix :)
