### ISSUE TITLE
Labelling of ember+ paths

### ISSUE THREAD

**Issue by phillipivan** [bitfocus/companion-module-generic-emberplus#16]
I have buttons with 6 or more ember+ actions stacked. It can be hard to keep track of which function is which. Is it possible to either (a) add a name / description to ember+ paths that persist across actions or (b) add a non functional description field to each action to make them easier to parse down the track.

**Comment by premultiply** [comment]
Maybe it would be easier to parse the full path copied from EmberPlusView including the textual representation by a regular expression.

That means you may enter something like `V*AP/controller_dsp[1]/system.snmp/parameters/idx_1/config.snmpTrapEnableMask [4096.1.39.4098.81921.2232]` and it would automatically extract `4096.1.39.4098.81921.2232` for internal processing but leave the full text path it in the field for human reference.

**Comment by phillipivan** [comment]
Good suggested. I have implemented this in 2.3.1
