### ISSUE TITLE
Ember+ doesn't seem to send to the type I set

### ISSUE THREAD

**Issue by mbaklor** [bitfocus/companion-module-generic-emberplus#2]
Hello,

I'm trying to use the companion with a system using Ember+, and I that if I set the action to Set Value String it gives me an error "0.3.0.1 is not an INTEGER value", so presumably it sends an integer instead of string? From the little and shallow testing I've done that seems to be the only type it doesn't send right.

Thanks
-mbaklor

**Comment by baltedewit** [comment]
I've fixed this in the module a while ago but still waiting for companion to upgrade the version of the module

**Comment by baltedewit** [comment]
Should be upgraded now.
