### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by zwerg1717** [bitfocus/companion-module-generic-emberplus#20]
Hi.

I use ember+ to control my DHD mixer. That works great. However, it would be much better if the mixer gave feedback and the button in Companion turned red when the channel on the mixer is on.
Is there a possibility?

**Comment by SimonHyde-BBC** [comment]
I've done exactly this in https://github.com/SimonHyde-BBC/companion-module-generic-emberplus

**Comment by mint-dewit** [comment]
PR is merged, hope to release this soon.
