### ISSUE TITLE
Ember+ Path with dot in Name

### ISSUE THREAD

**Issue by MatzeP** [bitfocus/companion-module-generic-emberplus#23]
Hi,

can anybody please help me.

I have lots of path which have dot in the label. Is ist possible to mask them or to set the Path with the number string?
I have learnd that I should replace the "/" to "."

V*AP/controller_dsp[1]/system.snmp/parameters/idx_1/config.snmpTrapEnableMask [4096.1.39.4098.81921.2232]

**Comment by premultiply** [comment]
The value to enter into the Path field is just `4096.1.39.4098.81921.2232`.

**Comment by MatzeP** [comment]
Hi,
nice to hear from you.
I have configure a Button
![image](https://github.com/bitfocus/companion-module-generic-emberplus/assets/25775637/a278488a-bbda-4b84-8a0a-117e066b6f3c)

_emberplus_: **SetValueBoolean**: Path=4096.1.39.4098.81921.2232
**LOG**: Instance/Wrapper/emberplus: Node 4096.1.39.4098.81921.2232 is not of type BOOLEAN

_emberplus_: **SetValueInteger**: Path=4096.1.39.4098.81921.2232
**LOG**: Instance/Wrapper/emberplus: Node 4096.1.39.4098.81921.2232 is not of type INTEGER

_emberplus_: **SetValueReal**: Path=4096.1.39.4098.81921.2232
**LOG**: Instance/Wrapper/emberplus: Node 4096.1.39.4098.81921.2232 is not of type REAL

_emberplus_:** **SetValueString**: Path=4096.1.39.4098.81921.2232
**LOG**: Instance/Wrapper/emberplus: Node 4096.1.39.4098.81921.2232 is not of type STRING

### Here is the Screenshot from Companion-LOG:
![image](https://github.com/bitfocus/companion-module-generic-emberplus/assets/25775637/f61c5f7a-cf84-4062-87a6-49eefa9ac3c6)


### Here is a Screenshot from EmberViewer v2.40.0.35
![image](https://github.com/bitfocus/companion-module-generic-emberplus/assets/25775637/4c8f33d1-5ae4-49c9-81dc-3feb43ea4e91)

I hope you can see what I do wrong.

**Comment by mint-dewit** [comment]
Can you try by setting an ENUM instead?

**Comment by phillipivan** [comment]
Closing as stale. Reopen if still an issue. Should work with ENUM as per prior comment.
