### ISSUE TITLE
Button suggestions

### ISSUE THREAD

**Issue by 152iq** [bitfocus/companion-module-generic-emberplus#25]
Suggestions for buttons. give the button a toggle state, such that press one sets value A and press 2 sets value B. i.e. true/false, 0/1.
Button press steps through list of values, i.e. filter values or channel pick off points (pre-eq, pre-fade, post fade)
Lamp tally from the ember values to reflect when other programming or parallel control sets the value. Multiple states and colors possible.
Button press to increment an integer value with tuneable value. (+1, +3, +10, -1, -3, -10)

**Comment by phillipivan** [comment]
Some of this can be done with expressions in version 2.3 at least for strings and integers.
