### ISSUE TITLE
Use Variable in values

### ISSUE THREAD

**Issue by jamesPenry** [bitfocus/companion-module-generic-emberplus#27]
Been using the "Set Value Interger" action resently for a volume control of the Lawo unit. but as i can only use numbers ive had to put alot of triggers (60 +) and other bits in to just inreimentaly increase or Decrease the volume value to send it as a number only. Idealy this can all be tieded up to a single simple expression if we could uses expressions and variables in the vlaue feilds of the actions and not just Intergers or strings.

**Comment by Lamebirdy** [comment]
Funny you mention this as I was literally trying to figure out the exact same thing.  I also want to put in the request for adding expressions or variables as values to send back to the ember parameter.  Trying to get a Lawo Mc2 console where I can control the fader levels of specific DSP channels from Companion using the rotary control on a streamdeck.  At the moment this was only able to be achieved with tons of triggers and isn't really feasible to do this in real life workflows where using a variable and expression would allow it to be very simple.

**Comment by jamesPenry** [comment]
Thats exactly what im trying to do and how i worked around it. Not with an Mc2, but still same idea.
