### ISSUE TITLE
Display path value on button

### ISSUE THREAD

**Issue by lenstar** [bitfocus/companion-module-generic-emberplus#3]
would it be possible to just get a path value on a bottom? Would like to monitor just some temputurs out a emberplus tree. Woul be nice to have something like $(emberplus:"path") in the bottom text field

**Comment by mbaklor** [comment]
Just following up on this, what is needed to make this happen? Is there anyone on hand who can do this? I don't know if I have the knowledge to make this adjustment but I'd like to know the scope before I try and take this on.

**Comment by baltedewit** [comment]
There is no reasonable way of doing this type of thing in companion currently as far as I know

**Comment by mattlamb99** [comment]
+1 this would be a very useful feature.
 Doesn't look like there is any way of getting any values from the ember tree with this, only set value and matrix connects

**Comment by lenstar** [comment]
so it's only sending, theres no way to do pull request on some id's of the ember+ tree every second or so?

**Comment by baltedewit** [comment]
Might be possible to add for companion 3.0, I think the feedback mechanism has changed there. I'd have to look into it further.

**Comment by Svein-sch** [comment]
+1
This would be a very nice feature to have!

**Comment by mint-dewit** [comment]
This has been added in module version 2.2.0
