### ISSUE TITLE
Connection Issue After Extended Device Downtime

### ISSUE THREAD

**Issue by schmidttho** [bitfocus/companion-module-generic-emberplus#30]
We have observed that when the device is turned off overnight and then powered on the next morning, the connection cannot be re-established. Even though the device is back online, no connection is made.

To restore the connection, we need to toggle the "Service" off and on again in the Companion interface. After doing so, the connection is immediately restored, and everything works perfectly.

**1. Timeout After Connection Loss**: Is there a set period after which the module stops attempting to reconnect if the device goes offline?
**2. Timeout Configuration:** The issue seems to occur after approximately 5 minutes without a connection. Is there an option to configure this timeout duration to allow for automatic reconnection after an extended device downtime? 
Please see the attached screenshot for reference:
![Compaion Fehler](https://github.com/user-attachments/assets/9e33a3c1-1c05-4091-96b0-28d36031b6cb)

- The module should automatically attempt to reconnect after the device comes back online, even after a long offline period.

- It would be helpful to have an option to configure the timeout duration for reconnection attempts to address this issue.

Thank you for the great work on this module!

**Comment by phillipivan** [comment]
We have encountered exactly the same issue.

**Comment by phillipivan** [comment]
I think your five minutes is spot on - it is occuring in the core emberplus-connection library.
Defined [here](https://github.com/nrkno/sofie-emberplus-connection/blob/896e655cdc499594030dcac9dc36ec4242b2a00d/src/Ember/Socket/S101Client.ts#L39). Actioned [here](https://github.com/nrkno/sofie-emberplus-connection/blob/896e655cdc499594030dcac9dc36ec4242b2a00d/src/Ember/Socket/S101Client.ts#L73-L86).

I will try and address this in the near future.

**Comment by phillipivan** [comment]
@schmidttho would you kindly try this build and let me know how you go.

[companion-module-generic-emberplus.zip](https://github.com/user-attachments/files/17053067/companion-module-generic-emberplus.zip)

**Comment by schmidttho** [comment]
First of all, thanks for your effort. :-)
Unfortunately, the issue persists. Even in the new version, the module times out after about 5 minutes and loses connection. Here is a corresponding screenshot from the log:
<img width="674" alt="image" src="https://github.com/user-attachments/assets/ebf7f3b5-f15a-41df-9275-6e3280aef77b">

10:49:10 Ember+ device is turned off
10:52:22 Ember+ device is turned back on

There is no log entry for turning it back on after 5 minutes. Only restarting the service through the Companion interface restores the connection.

**Comment by phillipivan** [comment]
Thanks for testing - I have limited chances to take our systems down to test this.

Was debug level turned on in that screen shot? If not, please make sure it is for any future logs as it will have some help info.

I will get another version together soon.

**Comment by phillipivan** [comment]
[companion-module-generic-emberplus.zip](https://github.com/user-attachments/files/17069562/companion-module-generic-emberplus.zip)
Thanks for your patience. Can you please try this. Unfortunately I wont have a chance to test it for a little while.

**Comment by phillipivan** [comment]
My colleague was able to test this, and the module reconnects after a 10 minute interruption. I will leave the ticket open a day or two for you to test, in the mean time I have issued a release for inclusion in betas.

**Comment by schmidttho** [comment]
Thank you so much for your effort. Unfortunately, I won’t be able to test it until Monday. I will provide feedback as soon as possible.

**Comment by phillipivan** [comment]
[companion-module-generic-emberplus_v2.4.0.zip](https://github.com/user-attachments/files/17074713/companion-module-generic-emberplus_v2.4.0.zip)
You might as well test with this version - on top of the re-connection issue, it adds bonjour device discovery and action recorder support.

**Comment by schmidttho** [comment]
First of all, a huge thanks for your support and all the hard work on the project!

Unfortunately, it doesn't seem to be running quite smoothly for me yet. After an Ember+ connection is interrupted, the log shows that a reconnect is established, but something still doesn’t seem to be working properly afterward.

I’ve tested this with Generic: Ember+ version 2.3.2 and 2.3.4, and both versions show the same issue. It might also be a problem on my end, of course.

I’m attaching the log in case it helps you identify the issue.

Thanks in advance for your help!

![image](https://github.com/user-attachments/assets/1f2eb74b-4c21-4e39-86b0-edc81a767995)
[Support-bundles.zip](https://github.com/user-attachments/files/17098318/Support-bundles.zip)

**Comment by phillipivan** [comment]
Hi @schmidttho i am a bit confused by the log in the screen shot.
This looks like it is going into fault as soon as the module is initialised? I thought the issue was the module failing to reconnect after a long interruption like the device being switch off for some time.
Also at the point where the connection is being refused can you please sanity check that ember plus viewer can open a connection?

Note to self - we should also re-register for all paths on reconnect.

**Comment by schmidttho** [comment]
@phillipivan ,
This is a new issue that occurs as soon as the device is deactivated and then reactivated, not after the device has been turned off for some time. To help clarify the issue, I’ve made a short video where I simulate turning off the device by deactivating the Ember+ interface on a SonoVTS monitor.

At the same time, I’m also running the EmberPlusViewer to show that the monitor is likely not the source of the problem.

Thanks for your efforts! I’m happy to assist with further tests if needed.

https://github.com/user-attachments/assets/0e9f09e1-cea8-4830-abbe-0f9b56404cd3

**Comment by phillipivan** [comment]
Ok.
Do you mind creating a git seperate issue for this behaviour and we can look at that. It would be especially helpful to know if that is new and if so what version it appeared in.

Second, assuming you connect successfully at all? Can you test to see if the original issue with the module failing to reconnect after the device has been off for some time is fixed?

With our gear I haven't seen any change or issues with the module connecting.

**Comment by phillipivan** [comment]
Now that I have had a chance to watch the video properly, here is what is happening:
- The module reconnects when the Ember plus interface is re-enabled, but the initial [queries on connect](https://github.com/bitfocus/companion-module-generic-emberplus/blob/7449cdf431cc6ae4a12e7af2b58aac293c47cdb1/src/index.ts#L136-L139) fail. Its not clear why this failure occurs - it is either something in the base ember-plus library or (I suspect) the device accepts a connection on port:9000 before it has fully spun up the ember plus provider and returns some kind of invalid response, or doesnt respond at all. The module then gives up.

This is a separate issue to giving up reconnect attempts after 5 minutes of failures. We validated the fix for that by disconnecting the ETH from one of our Ember+ devices, and reconnecting after 10 minutes, the module immediately reconnected. I would be grateful if you could confirm with the same or similar test.

**Comment by schmidttho** [comment]
Since version v2.4.3, the issue has occurred where no automatic reconnect happens after 10 minutes of disconnection, behaving exactly the same as in version v2.3.2. Instead, the module needs to be manually restarted to re-establish the connection.

**Comment by phillipivan** [comment]
Hi,

Can you please:

- confirm your testing process? Was it by disabling the ember+ interface as per the prior video.

- post the logs from an attempt covering the full timespan

- give the module at least 5m to reconnect once it's back online (it should be faster than this but one of the timers involved is this long)

Thanks

**Comment by phillipivan** [comment]
Please try this build. When I tested it quickly reconnected after a 10 minute interruption both in the case of removing the ETH cable, and stopping and starting the ember plus provider.
[companion-module-generic-emberplus_v2.4.3.zip](https://github.com/user-attachments/files/17124143/companion-module-generic-emberplus_v2.4.3.zip)

**Comment by phillipivan** [comment]
[companion-module-generic-emberplus_v2.4.4.zip](https://github.com/user-attachments/files/17126173/companion-module-generic-emberplus_v2.4.4.zip)

**Comment by schmidttho** [comment]
Version v2.4.4 works perfectly for me.
Many thanks for all your effort!

**Comment by phillipivan** [comment]
Great to hear.
