### ISSUE TITLE
emberplus: Matrix Connect or Set Connection, target values restricted

### ISSUE THREAD

**Issue by ft247** [bitfocus/companion-module-generic-emberplus#4]
Target value appears to be limited to 0-65535 - attempting to control an Ereca Stage Racer 2 and failing as targets are auto-generated and fixed 10-digit integers (reported by Ember+ Viewer and confirmed in its debug window).

Or is this a hard limitation in ember+, implying I've made a balls of it?

**Comment by baltedewit** [comment]
The limit was set in the module, I've upgraded it a while ago but it seems that hasn't made it into companion yet
