### ISSUE TITLE
Module gives up if inital queries on connection fail

### ISSUE THREAD

**Issue by phillipivan** [bitfocus/companion-module-generic-emberplus#40]
From #30
If the initial queries fail, for instance if the device is booting and hasn't fully spooled up the ember+ interface, the module does not try again.

**Comment by phillipivan** [comment]
Please test with this build.
[companion-module-generic-emberplus_v2.4.3.zip](https://github.com/user-attachments/files/17105982/companion-module-generic-emberplus_v2.4.3.zip)

**Comment by schmidttho** [comment]
The issue with "Module gives up if initial queries on connection fail" no longer occurs. However, now there's a timeout problem again. #30
