### ISSUE TITLE
ember+ Set Value Integer from Variable problem

### ISSUE THREAD

**Issue by Bart-SL** [bitfocus/companion-module-generic-emberplus#44]
I cannot use Set Value Integer from Variable function over ember+ connection.
It's not available from the action list. I can neither force companion to send $var in any Set Value command. Only numbers are accepted.
I'd like to send different (changable) values to an ember+ node. Any hint/help?

**Comment by phillipivan** [comment]
Hi Bart,

I think you are running an older module version which doesn't have it. Either download the build from the current release (2.4.4) and run it as a dev module, or use the 3.5 Beta.

Regards, 
Phillip

**Comment by Bart-SL** [comment]
Yes!  Thank you so much! It&#39;s such a great news!  Now I can see it&#39;s included in 2.4.4. I just wasn&#39;t aware the module has to be upgraded independentlty from companion itself.   thanks a lot and best regards!  I&#39;ll get back to it on Monday at work ;)  B. 
     
      
       
        Dnia 11 października 2024 21:40 phillipivan ***@***.***&gt; napisał(a):
       
    
       
         
 Hi Bart, 
 I think you are running an older module version which doesn&#39;t have it. Either download the build from the current release (2.4.4) and run it as a dev module, or use the 3.5 Beta. 
 Regards,  
Phillip

**Comment by phillipivan** [comment]
No worries, it will be included in 3.5 whenever that comes out, but not any future 3.4.X patch released because of the scope of changes.

I hope the new functions are useful for you.

**Comment by Bart-SL** [comment]
Thanks!  Works great ;) That&#39;s what I needed.  It&#39;d be even better to have set real from variable, but in this case INT are enough.   best regards  B  
     
      
       
        Dnia 12 października 2024 11:30 phillipivan ***@***.***&gt; napisał(a):
       
    
       
         
 Closed  github.com #44  as completed.

**Comment by phillipivan** [comment]
If you want a Set Real from Variable action, please create a separate issue for it. It shouldn't be hard to implement, but you will need to do some testing as none of the ember+ providers I work with have Real parameters.

There was some discussion recently on the ember+ google group that revealed the reference implementations of real encoding for ember+ are all incorrect according to the standard. Given how long ember+ has been around I took this as an indication that real parameters are used relatively infrequently.

**Comment by Bart-SL** [comment]
Hello,   well... I work with Lawo PowerCores and Vistool software. There are some ember+ Real parameters available (eg. fader position in dB, which I wanted to use). But in this particular case I can control it by INT value (as fader motor position) so it&#39;s not a big deal.  But if it&#39;s not a problem to program Real from Variable in Companion maybe it&#39;ll be worth to include it ;)   anyway thank you very much again! This is such a powerful combination of ember+/Lawo/Companion that creates actually infinite possibilities.   best regards!   Dnia 14 października 2024 23:11 phillipivan ***@***.***&gt; napisał(a):   If you want a Set Real from Variable action, please create a separate issue for it. It shouldn&#39;t be hard to implement, but you will need to do some testing as none of the ember+ providers I work with have Real parameters.  There was some discussion recently on the ember+ google group that revealed the reference implementations of real encoding for ember+ are all incorrect according to the standard. Given how long ember+ has been around I took this as an indication that real parameters are used relatively infrequently.  —  Reply to this email directly,  github.com view it on GitHub , or  github.com unsubscribe .  You are receiving this because you authored the thread. Message ID:  &lt;bitfocus/companion-module-generic-emberplus/issues/44/2412351387 @ github . com&gt;

**Comment by phillipivan** [comment]
Please create a separate issue for this and I will post a module build for you to test and report back on.
