### ISSUE TITLE
Enter path error

### ISSUE THREAD

**Issue by Nico96R** [bitfocus/companion-module-generic-emberplus#6]
Hello there,

I'm experiencing problems with my ember+ devices. Unfortunately I'm not entering the right path and I can not find anything about that in the README.md.

I'm using a LAWO PowerCore with ember+. I See the right path in my EmBER+ Viewer and can change the value there. But when I enter the exact same path in Companion, I get the following error.
![Bildschirmfoto 2022-03-10 um 11 44 30](https://user-images.githubusercontent.com/4738301/157646423-b1267711-d278-43b4-b569-58aad5d06f96.png)

<img width="596" alt="Bildschirmfoto 2022-03-10 um 11 43 59" src="https://user-images.githubusercontent.com/4738301/157646451-2a5d66d9-397c-4bc9-9416-060b7dc7e814.png">

![ember+viewer_2](https://user-images.githubusercontent.com/4738301/157646480-dd739ccb-fa0f-476b-a488-000df0a38652.PNG)

What am I doing wrong?

**Comment by Nico96R** [comment]
Works in the newest beta version, but not in the stable release 2.1.4

**Comment by baltedewit** [comment]
This should work in 2.2 release then.
