### ISSUE TITLE
mismatch with type Boolean

### ISSUE THREAD

**Issue by domiFR** [bitfocus/companion-module-generic-emberplus#7]
Hi,

I tried to configure a button to set a boolean value, but it seems that the parameter type (boolean) is not recognized
![01](https://user-images.githubusercontent.com/107393989/173310577-8b60c143-d3d6-42df-95d5-e182c8585cd1.png)
![02](https://user-images.githubusercontent.com/107393989/173310608-5487e164-a597-4806-afa1-a841fa88a60c.png)
![03](https://user-images.githubusercontent.com/107393989/173310616-491cd83d-c600-4fad-8503-6f14bc1989b8.png)

**Comment by Brunhilde** [comment]
Could you export the XML output of ember+ viewer? There are some additional hints that may help. You can also try my fork of this module, the warning will give addition information about the expected type.

**Comment by domiFR** [comment]
[module103.zip](https://github.com/bitfocus/companion-module-generic-emberplus/files/10011445/module103.zip)
Hi, here is the XML output.

Just to let you know, we use now a workaround : we install NodeJS, and we use the _"internal: Run shell path (local)" to run javascript scripts based on DeutscheSoft Ember+ implementation (https://github.com/DeutscheSoft/ember-plus). This works fine.

**Comment by phillipivan** [comment]
@domiFR can you please confirm if this is still an issue with the current version?

**Comment by phillipivan** [comment]
Closing as stale. I can successfully set boolean values in recent versions. Please update if this is still occurring with version 2.3.1 and I will reopen.
