### ISSUE TITLE
Controlling phone Hybrid

### ISSUE THREAD

**Issue by CostasColombus** [bitfocus/companion-module-generic-emberplus#8]
We try to control a telephone hybrid:

- While connecting successfully and
- controlling it possible the hybrid with EmberPlusView-2.40.0.30
- Companion will always have an error:
- ` Parameter 1.2.3.3 not found or not a parameter`
- `1.2.3.3` being the path, used without problems with EmberPlusView
![image](https://user-images.githubusercontent.com/53226540/186304519-06090351-be56-4483-b2ac-082158f740db.png)

**Comment by baltedewit** [comment]
Node `1.2.3.3` in your device is not a parameter, it's a function. There is no way to call ember+ functions with this companion

**Comment by CostasColombus** [comment]
Thanks a lot for the clarification.
I found a workaround where it has chances to work properly
